# Rede Neural na prática.

In [1]:
# importando as bibliotecas:
    
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils


In [2]:
# Carregamento da base de dados e criação dos previsores (variáveis independentes - X) e da classe ( variável dependente - y):

base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# Transformação da classe para o formato 'dummy', pois tomes uma rede neural com 3 neurônios na camada de saída:

classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
# Divisão da base de dados entre trinamento e teste (30% para testar e 70% para treinar)

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe_dummy, test_size = 0.3, random_state = 0)

In [23]:
# Criação da estrutura da rede neural com classe Sequential (sequência de camadas):

modelo = Sequential()

# Primeira camada oculta, 5 neuronios, 4 neuronios de entrada:

modelo.add(Dense(units = 5, input_dim = 4))

# Segunda camada oculta:

modelo.add(Dense(units = 4))

# Terceira camada oculta:

# Função sotmax porque temos um problema de classificação com mias de duas classes é gerado uma probabilidade em cada neuronio:

modelo.add(Dense(units = 3, activation = 'softmax'))

In [24]:
# Visualização da estrutura de rede neural:

modelo.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_7 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 15        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [25]:
# Configuração dos par{ametros da rede neural (adam = algoritimo para atualizar os pesos e loss = cálculo do erro):

modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data):

modelo.fit(X_treinamento, y_treinamento, epochs = 1000, validation_data = (X_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 2s 150ms/step - loss: 4.3621 - accuracy: 0.3238 - val_loss: 3.4499 - val_accuracy: 0.3556
Epoch 2/1000
4/4 [==============================] - 0s 25ms/step - loss: 4.0226 - accuracy: 0.3238 - val_loss: 3.1686 - val_accuracy: 0.3556
Epoch 3/1000
4/4 [==============================] - 0s 28ms/step - loss: 3.7082 - accuracy: 0.3238 - val_loss: 2.9131 - val_accuracy: 0.3556
Epoch 4/1000
4/4 [==============================] - 0s 39ms/step - loss: 3.4249 - accuracy: 0.3048 - val_loss: 2.6889 - val_accuracy: 0.3556
Epoch 5/1000
4/4 [==============================] - 0s 33ms/step - loss: 3.1504 - accuracy: 0.2571 - val_loss: 2.4955 - val_accuracy: 0.1778
Epoch 6/1000
4/4 [==============================] - 0s 37ms/step - loss: 2.9068 - accuracy: 0.1048 - val_loss: 2.3268 - val_accuracy: 0.0444
Epoch 7/1000
4/4 [==============================] - 0s 38ms/step - loss: 2.7036 - accuracy: 0.0095 - val_loss: 2.1785 - val_accuracy: 0.0444
Epoch 8/1000

In [26]:
# Previsões e mudar a variável para True ou False de acordo com threshold 0.5:

previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [27]:
# Como é um problema com três saidas, precisamos buscar a posição que possui o maior valor (são retornados 3 valores)

y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsoes_matrix = [np.argmax(t) for t in previsoes]

In [28]:
# Geração da matriz de confusão:

confusao = confusion_matrix(y_teste_matrix, y_previsoes_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)